### ISSUE TITLE
Quete depart Orc

### ISSUE THREAD

**Issue by Drakking666** [Last-Kingdom/bugtracker#10]
Zone: dans la grote au nord de la vallée des épreuves
quete 'la pioche de Thazz'ril' on ne peux la récupéré

**Comment by buddyqc69** [comment]
Je vais vérifier cela merci !

**Comment by buddyqc69** [comment]
- [ ] Prendre la quête
- [ ] Se rendre à l'endroit concerné
- [ ] Gameobject fonctionnel ?
- [ ] Prendre l'item pour la quête fonctionnel ?
- [ ] Validation du fonctionnement de la quête ?
