### ISSUE TITLE
[DB/QUEST] Quêtes de départ des chevaliers de la mort

### ISSUE THREAD

**Issue by Drakking666** [Last-Kingdom/bugtracker#12]
Ou: Quete depart des Chevalier de la mort
Quete: 'la lame runique blasonnée' 
imposible de prendre l'epée à lame runique (2second quete)

**Comment by buddyqc69** [comment]
peux tu vérifier si cela fonctionne ? avec photo en preuve, merci

**Comment by Drakking666** [comment]
![image](https://user-images.githubusercontent.com/59938980/141537669-5e25786e-db3d-44f5-9bab-764537afad4a.png)
Toujours pas fonctionnel

**Comment by buddyqc69** [comment]
Quelle sont les étapes qui fonctionne et celle qui ne fonctionne pas?

**Comment by ForceQc** [comment]
Ya aucune étape, la quête nous demande une épée sur un Râtelier et elle n'y est pas

**Comment by buddyqc69** [comment]
Je vais vérifier cela, merci

**Comment by buddyqc69** [comment]
est-ce que le problème à été résolu ? merci
