### ISSUE TITLE
problème de loots 

### ISSUE THREAD

**Issue by Drakking666** [Last-Kingdom/bugtracker#8]
Zone: orc (Durotar) Tête de pont de Guet-du Nord, Donjon de Tiragarde
a ouest de Sen'jin, et a son nord, sud est Tranchecolline.
'guet du nord' humanoide type humain
5mob 0loot

**Comment by buddyqc69** [comment]
Ya combien de pnj sans loot? Les quelles? Et c'est quoi leur ID creature avec wowhead merci
