### ISSUE TITLE
[Bad/Info] pierre de foyer 

### ISSUE THREAD

**Issue by Drakking666** [Last-Kingdom/bugtracker#9]
la pierre de foyer des trolls emmène sous map au ravin des éboulis au Serres-Rocheuses. resusite Sentier des Tisseuses 
Si on peux teleporté 'Aelias' & 'Testeur' Zone depart trolls

**Comment by buddyqc69** [comment]
il faut donc être dans la zone de départ des troll pour que cela arrive ?
